"""
AI Validator — BedrockPromptHandler (destination reconstruction).

Reconstructed from the authoritative recovered source
(local-only/evidence/ai-validator-recovery/git-history/BedrockPromptHandler.py),
adapted for the destination account (102726256311) architecture.

Behavior preserved:
  API Gateway (HTTP API) event -> extract prompt -> Bedrock Agent invoke_agent
  -> stream completion chunks -> HTTP 200 {"response": ...}

Frozen destination decisions applied:
  - Authentication is owned by the API Gateway JWT authorizer. This handler
    does NOT verify or decode JWTs and has no PyJWT dependency.
  - Legacy CloudFront signed-URL feature DROPPED: no SSM private key read, no
    CloudFrontSigner, no rsa, no cloudfront_signed_url in the response.
  - Bedrock Agent id/alias come from environment (no hard-coded source IDs).
  - No hard-coded source account / Cognito / CloudFront values.

Runtime: python3.12, boto3 provided by the Lambda runtime (no third-party deps).
"""

import json
import os
import uuid

import boto3
from botocore.exceptions import ClientError

_ALLOWED_ORIGIN = os.environ.get("ALLOWED_ORIGIN", "https://ai.usmissionhero.com")

# CORS: API Gateway owns CORS for the HTTP API. These headers are a minimal
# fallback so direct/proxy responses remain browser-usable; they intentionally
# reference the destination application origin only.
_CORS_HEADERS = {
    "Content-Type": "application/json",
    "Access-Control-Allow-Origin": _ALLOWED_ORIGIN,
    "Access-Control-Allow-Headers": "Content-Type,Authorization",
    "Access-Control-Allow-Methods": "OPTIONS,POST",
}


class ConfigurationError(Exception):
    """Raised when required runtime configuration is missing."""


def _require_env(name):
    value = os.environ.get(name)
    if not value:
        # Fail clearly; no fake default for required deployment configuration.
        raise ConfigurationError(f"Missing required environment variable: {name}")
    return value


def _get_request(event):
    """Return (method, body_str) for HTTP API v2 or REST v1 proxy events."""
    event = event or {}
    request_context = event.get("requestContext") or {}
    if "http" in request_context:  # HTTP API v2
        method = (request_context.get("http") or {}).get("method", "")
        body = event.get("body")
        if event.get("isBase64Encoded") and body:
            import base64

            body = base64.b64decode(body).decode("utf-8", errors="replace")
        return method, body
    # REST API v1 proxy
    return event.get("httpMethod", ""), event.get("body")


def _response(status_code, payload):
    return {
        "statusCode": status_code,
        "headers": _CORS_HEADERS,
        "body": json.dumps(payload),
    }


def _error(message, status_code=500):
    return _response(status_code, {"error": message})


def invoke_bedrock_agent(prompt, agent_id, agent_alias_id):
    """Invoke the Bedrock Agent and concatenate the streamed completion text."""
    client = boto3.client("bedrock-agent-runtime")
    response = client.invoke_agent(
        agentId=agent_id,
        agentAliasId=agent_alias_id,
        sessionId=str(uuid.uuid4()),
        inputText=prompt,
    )

    response_text = ""
    for chunk_event in response.get("completion", []):
        chunk = chunk_event.get("chunk") if isinstance(chunk_event, dict) else None
        if chunk and "bytes" in chunk:
            response_text += chunk["bytes"].decode("utf-8", errors="replace")

    return response_text or "No response generated by the agent."


def lambda_handler(event, context=None):
    try:
        # Required destination configuration (wired by Terraform; no defaults).
        agent_id = _require_env("BEDROCK_AGENT_ID")
        agent_alias_id = _require_env("BEDROCK_AGENT_ALIAS_ID")
    except ConfigurationError as exc:
        # Configuration problem is a server-side (500) condition, logged plainly.
        print(f"Configuration error: {exc}")
        return _error("Service is not correctly configured.", 500)

    method, raw_body = _get_request(event)

    # CORS preflight (API Gateway normally handles this; safe fallback).
    if str(method).upper() == "OPTIONS":
        return {"statusCode": 204, "headers": _CORS_HEADERS, "body": ""}

    # Authentication is enforced by the API Gateway JWT authorizer upstream.
    # This handler does not re-verify tokens.

    try:
        body_json = json.loads(raw_body or "{}")
    except (ValueError, TypeError):
        return _error("Invalid JSON in request body.", 400)

    prompt = (body_json.get("prompt") or "").strip()
    if not prompt:
        return _error("Missing 'prompt' parameter in the request body.", 400)

    try:
        response_text = invoke_bedrock_agent(prompt, agent_id, agent_alias_id)
    except ClientError as exc:
        # Do not leak internal AWS detail to the client.
        code = exc.response.get("Error", {}).get("Code", "Unknown")
        print(f"Bedrock ClientError: {code}: {exc}")
        return _error("Upstream AI service error.", 502)
    except Exception as exc:  # noqa: BLE001 - final safety net, sanitized to client
        print(f"Unhandled error invoking agent: {exc}")
        return _error("Internal error.", 500)

    return _response(200, {"response": response_text})
